config/routes.rb
Rails.application.routes.draw do
  resources :gardens do
    resources :plants, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/garden.rb
class Garden < ApplicationRecord
  has_many :plants
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :garden
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  before_action :set_garden, only: %i(show edit update destroy)
  
  def index
    @gardens = Garden.all
  end

  def show
    @plant = Plant.new
  end

  def new
    @garden = Garden.new
  end

  def create
    @garden = Garden.new(garden_params)
    if @garden.save
      redirect_to gardens_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
  end

  def destroy
  end

  private
  
  def garden_params
    params.require(:garden).permit(:name, :image_url)
  end

  def set_garden
    @garden = Garden.find(params[:id])
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController

  def create
    @plant = Plant.new(plant_params)
    @garden = Garden.find(params[:garden_id])
    @plant.garden = @garden
    if @plant.save
      redirect_to @garden
    else
      render "gardens/show", status: :unprocessable_entity
    end
  end

  private

  def plant_params
    params.require(:plant).permit(:name, :image_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/gardens/edit.html.erb
<h1>Gardens#edit</h1>
<p>Find me in app/views/gardens/edit.html.erb</p>

app/views/gardens/index.html.erb
<div class="container">
  <h2>Gardens</h2>
  <% @gardens.each do |garden| %>
    <%= garden.name %>
    <%= garden.image_url %>
    <%= link_to "View details", garden_path(garden) %>
  <% end %>
</div>

app/views/gardens/new.html.erb
<div class="container">
  <%= simple_form_for @garden do |f| %>
    <%= f.input :name %>
    <%= f.input :image_url %>
    <%= f.submit %>
  <% end %>
</div>

app/views/gardens/show.html.erb
<div class="banner" style="background-image:url(<%= @garden.image_url%>)">
  <h1><%= @garden.name %> </h1>
</div>
  
<div class="container">
  <div class="row">
      <% @garden.plants.each do |plant| %>
        <div class="col-4 card" style="background-image:url(<%= plant.image_url%>)">
          <h3><%= plant.name %> </h3>
        </div>
      <% end %>
    </div>
  </div>
 <hr>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-4">
      <%= simple_form_for [@garden, @plant] do |f|%>
        <%= f.input :name %>
        <%= f.input :image_url %>
        <%= f.submit class: "btn btn-warning"%>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GardensAndPlants</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>